### ISSUE TITLE
About Sparc based devices

### ISSUE THREAD

**Issue by andrasdee** [rdynsxtrs/rn4bin#9]
Hi!
Thanks for all that effort.

If I wanted to learn how to do what you have done, and create the update for TLSv1.2 for Sparc based devices, then how do I start learning to do that?
Are there any tutorials out there, that would get me close to learn the process you have done for the x86 based devices?
Have you created any notes on what/how you have done for x86, that you would be happy to share?

Thanks,
Andras

**Comment by RustyDust** [comment]
> If I wanted to learn how to do what you have done, and create the update for TLSv1.2 for Sparc based devices, then how do I start learning to do that? 

Basically all you need to know is how to build packages for Debian based Linux distributions. There's a lot of information on that topic available.

Then you'd go and pick the parts you want or need to replace from a newer Debian distribution (Stretch or Buster would be good choices) and try to backport those to the ReadyNAS. Backporting in this case mostly means "compile them on the NAS" but may require you to backport additional stuff, depending on what your current target requires.

> Have you created any notes on what/how you have done for x86, that you would be happy to share?

Maybe this will get you started: https://github.com/rdynsxtrs/rn4src-x86/tree/develop

That said, chances to port TLS v1.2+ support to Sparc based ReadyNAS devices are close to zero because of the age of these systems. They simply don't have a recent enough base operating system and thus totally outdated base libraries which aren't adequate to build the newer OpenSSL libraries you'd need.
